config/routes.rb
Rails.application.routes.draw do
  resources :developers
  resources :fors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :developer_languages, dependent: :destroy
  has_many :languages, through: :developer_languages

  has_many :developer_programming_languages, dependent: :destroy
  has_many :programming_languages, through: :developer_programming_languages

  validates :email, presence: true, uniqueness: true
end

def self.search(search)
	# if search
		where("name LIKE ? OR ingredients LIKE ? OR cooking_instructions LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
	# else 
	# 	find(:all)
	# end
end

app/models/developer_language.rb
class DeveloperLanguage < ApplicationRecord
  belongs_to :developer, inverse_of: :developer_languages
  belongs_to :language, inverse_of: :developer_languages
end

app/models/developer_programming_language.rb
class DeveloperProgrammingLanguage < ApplicationRecord
  belongs_to :developer
  belongs_to :programming_language
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :developer_languages, dependent: :destroy
  has_many :developers, through: :developer_languages

  validates :code, presence: true, uniqueness: true
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
  has_many :developer_programming_languages, dependent: :destroy
  has_many :developers, through: :developer_programming_languages

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: [:show, :edit, :update, :destroy]

  # GET /developers
  # GET /developers.json
  def index
    @search_form = SearchForm.new(search_params)
    @developers = @search_form.search
  end

  # GET /developers/1
  # GET /developers/1.json
  def show
  end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit
  end

  # POST /developers
  # POST /developers.json
  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: 'Developer was successfully created.' }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developers/1
  # PATCH/PUT /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to @developer, notice: 'Developer was successfully updated.' }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1
  # DELETE /developers/1.json
  def destroy
    @developer.destroy
    respond_to do |format|
      format.html { redirect_to developers_url, notice: 'Developer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def developer_params
      params.require(:developer).permit(:email)
    end

    
    def search_params
      return {} if params[:search_form].blank?
      params.require(:search_form).permit(:email, :prog_lang, :language_code)
    end
end

app/controllers/fors_controller.rb
class ForsController < ApplicationController
  before_action :set_for, only: [:show, :edit, :update, :destroy]

  # GET /fors
  # GET /fors.json
  def index
    @fors = For.all
  end

  # GET /fors/1
  # GET /fors/1.json
  def show
  end

  # GET /fors/new
  def new
    @for = For.new
  end

  # GET /fors/1/edit
  def edit
  end

  # POST /fors
  # POST /fors.json
  def create
    @for = For.new(for_params)

    respond_to do |format|
      if @for.save
        format.html { redirect_to @for, notice: 'For was successfully created.' }
        format.json { render :show, status: :created, location: @for }
      else
        format.html { render :new }
        format.json { render json: @for.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fors/1
  # PATCH/PUT /fors/1.json
  def update
    respond_to do |format|
      if @for.update(for_params)
        format.html { redirect_to @for, notice: 'For was successfully updated.' }
        format.json { render :show, status: :ok, location: @for }
      else
        format.html { render :edit }
        format.json { render json: @for.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fors/1
  # DELETE /fors/1.json
  def destroy
    @for.destroy
    respond_to do |format|
      format.html { redirect_to fors_url, notice: 'For was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_for
      @for = For.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def for_params
      params.require(:for).permit(:Developer, :null, :unique)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/fors_helper.rb
module ForsHelper
end

app/views/developers/_form.html.erb
<%= form_with(model: developer, local: true) do |form| %>
  <% if developer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
      <% developer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :developer_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/developers/edit.html.erb
<h1>Editing Developer</h1>

<%= render 'form', developer: @developer %>

<%= link_to 'Show', @developer %> |
<%= link_to 'Back', developers_path %>

app/views/developers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Developers</h1>
<br>
<%= form_for @search_form, url: developers_path, method: :get do |f| %>
  Email : <%= f.text_field :email %>
  Language Code : <%= f.text_field :language_code %>
  Programming Languages : <%= f.text_field :prog_lang %>
  <%= f.submit "Search" %>
<% end %>
<br>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Languages</th>
      <th>Programming Languages</th>
      <th>Config</th>
    </tr>
  </thead>

  <tbody>
    <% if @developers.present? %>
    <% @developers.each do |developer| %>
      <tr>
        <td><%= developer.email %></td>
        <td>
          <% developer.languages.each do |language_code| %>
            <%= language_code.code %>
          <% end %>
        </td>
        <td>
          <% developer.programming_languages.each do |pro_lang| %>
            <%= pro_lang.name %>
          <% end %>
        </td>
        <td><%= link_to 'Show', developer %>
          <%= link_to 'Edit', edit_developer_path(developer) %>
          <%= link_to 'Destroy', developer, method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
      </tr>
    <% end %>
    <% else %>
      <tr>
        <td>No result</td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Developer', new_developer_path %>

app/views/developers/new.html.erb
<h1>New Developer</h1>

<%= render 'form', developer: @developer %>

<%= link_to 'Back', developers_path %>

app/views/developers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @developer.email %>
</p>

<%= link_to 'Edit', edit_developer_path(@developer) %> |
<%= link_to 'Back', developers_path %>

app/views/fors/_form.html.erb
<%= form_with(model: for, local: true) do |form| %>
  <% if for.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(for.errors.count, "error") %> prohibited this for from being saved:</h2>

      <ul>
      <% for.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Developer %>
    <%= form.text_field :Developer, id: :for_Developer %>
  </div>

  <div class="field">
    <%= form.label :null %>
    <%= form.text_field :null, id: :for_null %>
  </div>

  <div class="field">
    <%= form.label :unique %>
    <%= form.text_field :unique, id: :for_unique %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fors/edit.html.erb
<h1>Editing For</h1>

<%= render 'form', for: @for %>

<%= link_to 'Show', @for %> |
<%= link_to 'Back', fors_path %>

app/views/fors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fors</h1>

<table>
  <thead>
    <tr>
      <th>Developer</th>
      <th>Null</th>
      <th>Unique</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fors.each do |for| %>
      <tr>
        <td><%= for.Developer %></td>
        <td><%= for.null %></td>
        <td><%= for.unique %></td>
        <td><%= link_to 'Show', for %></td>
        <td><%= link_to 'Edit', edit_for_path(for) %></td>
        <td><%= link_to 'Destroy', for, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New For', new_for_path %>

app/views/fors/new.html.erb
<h1>New For</h1>

<%= render 'form', for: @for %>

<%= link_to 'Back', fors_path %>

app/views/fors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Developer:</strong>
  <%= @for.Developer %>
</p>

<p>
  <strong>Null:</strong>
  <%= @for.null %>
</p>

<p>
  <strong>Unique:</strong>
  <%= @for.unique %>
</p>

<%= link_to 'Edit', edit_for_path(@for) %> |
<%= link_to 'Back', fors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Developersearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>